### LogiTrans Express — ms-auth (puerto 8001)
@base = http://localhost:8001
@token = 7e9c92f1456aa329b7fe03827c0c2b14a9f6b1b77155045b5469fd8aedd3f0c8

### 1. Login
POST {{base}}/auth/login
Content-Type: application/json

{
  "login": "admin",
  "password": "admin123"
}

### 2. Validar token
GET {{base}}/auth/validate
Authorization: Bearer {{token}}

### 3. Logout
POST {{base}}/auth/logout
Authorization: Bearer {{token}}

### 4. Listar usuarios
GET {{base}}/usuarios
Authorization: Bearer {{token}}

### 5. Crear usuario
POST {{base}}/usuarios
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "Operador Uno",
  "correo": "operador@logitrans.com",
  "usuario": "operador1",
  "password": "pass123",
  "rol": "operador"
}