### ms-conductores — LogiTrans Express (puerto 8002)

@base = http://localhost:8002
@token = 7e9c92f1456aa329b7fe03827c0c2b14a9f6b1b77155045b5469fd8aedd3f0c8

### 0. Health check
GET {{base}}/

###

### 1. Listar todos los conductores
GET {{base}}/conductores
Authorization: Bearer {{token}}

###

### 2. Obtener conductor por ID
GET {{base}}/conductores/2
Authorization: Bearer {{token}}

###

### 3. Crear conductor (POST)
POST {{base}}/conductores
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nombres": "Nicolas",
    "apellidos": "Tamayo",
    "documento": "1011084879",
    "telefono": "3213250592",
    "correo": "nicolas@logitrans.com",
    "numero_licencia": "LIC-001",
    "categoria_licencia": "C2",
    "fecha_vencimiento_licencia": "2027-12-31",
    "estado": "disponible"
}

###

### 4. Actualizar conductor (PUT)
PUT {{base}}/conductores/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nombres": "Carlos Alberto",
    "apellidos": "Ramírez",
    "telefono": "3009999999"
}

###

### 5. Cambiar estado (PATCH)
PATCH {{base}}/conductores/2/estado
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "estado": "en_ruta"
}

###

### 6. Eliminar conductor (DELETE)
DELETE {{base}}/conductores/1
Authorization: Bearer {{token}}