### ms-vehiculos — LogiTrans Express (puerto 8003)

@base = http://localhost:8003
@token = 42646305376fa2c6cf852c13b0095aaa72392410e6135e316ed81d17b5f20ed6

### 0. Health check
GET {{base}}/

###

### 1. Listar vehículos
GET {{base}}/vehiculos
Authorization: Bearer {{token}}

###

### 2. Obtener vehículo por ID
GET {{base}}/vehiculos/2
Authorization: Bearer {{token}}

###

### 3. Crear vehículo
POST {{base}}/vehiculos
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "placa": "ABC133",
    "tipo": "Moto",
    "capacidad_kg": 500,
    "marca": "Yamaha",
    "modelo": "NKZ",
    "anio": 2022,
    "estado": "disponible"
}

###

### 4. Actualizar vehículo
PUT {{base}}/vehiculos/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "marca": "Ford",
    "modelo": "Cargo",
    "anio": 2021
}

###

### 5. Cambiar estado
PATCH {{base}}/vehiculos/2/estado
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "estado": "mantenimiento"
}

###

### 6. Eliminar vehículo
DELETE {{base}}/vehiculos/1
Authorization: Bearer {{token}}