### ms-vehiculos — LogiTrans Express (puerto 8003)

@base = http://localhost:8003
@token = 7e9c92f1456aa329b7fe03827c0c2b14a9f6b1b77155045b5469fd8aedd3f0c8

### 0. Health Check
GET {{base}}/

###

### 1. Listar vehículos
GET {{base}}/vehiculos
Authorization: Bearer {{token}}

###

### 2. Obtener vehículo por ID
GET {{base}}/vehiculos/1
Authorization: Bearer {{token}}

###

### 3. Crear vehículo
POST {{base}}/vehiculos
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "placa": "DEF456",
    "tipo_vehiculo": "Camion",
    "capacidad_carga": 4500,
    "modelo": "2024",
    "marca": "Chevrolet",
    "estado": "disponible"
}

###

### 4. Actualizar vehículo
PUT {{base}}/vehiculos/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "marca": "Ford",
    "modelo": "2025",
    "capacidad_carga": 5000
}

###

### 5. Cambiar estado del vehículo
PATCH {{base}}/vehiculos/1/estado
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "estado": "mantenimiento"
}

###

### 6. Eliminar vehículo
DELETE {{base}}/vehiculos/1
Authorization: Bearer {{token}}